global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hoops-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hoops-backend:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['hoops-node-exporter:9100']
